const { EMAIL_FROM_INVITATION, EMAIL_SUBJECT_INVITATION, URL_FRONT, MQ_EXCHANGE_INVITATION, MQ_HOST_INVITATION } = process.env;
module.exports = {
  from: EMAIL_FROM_INVITATION,
  subject: EMAIL_SUBJECT_INVITATION,
  frontendUrl: URL_FRONT,
  hostMQ: MQ_HOST_INVITATION,
  exchangeMQ: MQ_EXCHANGE_INVITATION
};

