const { EMAIL_FROM_SUBSCRIPTION, EMAIL_SUBJECT_SUBSCRIPTION, MQ_EXCHANGE_SUBSCRIPTION, MQ_HOST_SUBSCRIPTION } = process.env;
module.exports = {
  from: EMAIL_FROM_SUBSCRIPTION,
  subject: EMAIL_SUBJECT_SUBSCRIPTION,  
  hostMQ: MQ_HOST_SUBSCRIPTION,
  exchangeMQ: MQ_EXCHANGE_SUBSCRIPTION
};