version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - my-network
  app:
    depends_on:
      - postgres         
      - rabbitmq
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - RDS_HOSTNAME=postgres
      - RDS_USERNAME=$POSTGRES_USER
      - RDS_PASSWORD=$POSTGRES_PASSWORD
      - RDS_DB_NAME=$POSTGRES_DATABASE
      - RDS_PORT=$POSTGRES_DOCKER_PORT      
      - MQ_HOST_INVITATION=amqp://rabbitmq
      - MQ_EXCHANGE_INVITATION=INVITATION
      - MQ_HOST_SUBSCRIPTION=amqp://rabbitmq
      - MQ_EXCHANGE_SUBSCRIPTION=SUBSCRIPTION
    stdin_open: true
    tty: true
    networks:
      - my-network  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my-network
volumes:
  db:
  rabbitmq_data:
  
networks:
  my-network:
    driver: bridge
