version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - my-network
  app:
    depends_on:
      - postgres
      - redis
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=postgres
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DATABASE
      - DB_PORT=$POSTGRES_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - my-network
  redis:
    image: 'redis:latest'
    ports:
      - "$REDIS_DOCKER_PORT:$REDIS_DOCKER_PORT"
    volumes:
      - redis-data:/data
    networks:
      - my-network
volumes:
  db:
  redis-data:
networks:
  my-network:
    driver: bridge
